/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs480.calculator.project;

import javax.swing.JOptionPane;

/**
 *
 * @author Chris
 */
public class CalcDisplayFrame extends javax.swing.JFrame {

    private Calculator myCalculator;
    private StringBuilder displayString;
    private int numLeftParen; //unmatched left parentheses count - when a matching right parentheses is used, decrement
    
    public CalcDisplayFrame() {
        myCalculator = new Calculator();
        displayString = new StringBuilder();
        numLeftParen = 0;
        initComponents();
    }

    
    //Number button handler
    private void numButtonHandler(String num){
        displayString.append(num);
        updateDisplay();
    }
    
    private void parenHandler(String paren){
        if(paren.equals("(")){
            numLeftParen++;
            displayString.append(paren);
        }
        else if(paren.equals(")")){
            if(numLeftParen > 0){
                numLeftParen--;
                displayString.append(paren);
            }
        }
        updateDisplay();
    }
    
    //operator handler
    private void operatorButtonHandler(String operator){
        switch(operator){
            case "+": 
            case "-": 
            case "*": 
            case "/": 
                if(checkOperatorStatus()){
                    displayString.append(operator);
                    updateDisplay();
                }
            break;
            
            case "=":
                equalsHandler();
            break;
            
            case "C": 
                resetCalc();
                updateDisplay();
            break;
            default: throw new RuntimeException("YOU BROKE THE CALCULATOR! CONGRATULATIONS!");
        }
    }
    
    private void updateDisplay(){
        if(displayString.length() > 0){
            displayFunctionLabel.setText(displayString.toString());
        }else{
            displayFunctionLabel.setText("0");
        }
    }
    
    //Return true only if it's safe to add a new operator to the string
    //Currently, only safe to add a new operator if the display string is longer than zero (can't start with an operator) or if the last character
    //in the string is a digit or a closing parentheses
    private boolean checkOperatorStatus(){
        boolean safeOperator = false;
        
        if(displayString.length() > 0 && Character.toString(displayString.charAt(displayString.length()-1)).matches("[0-9)]")){
            safeOperator = true;
        }
        
        return safeOperator;
    }
    
    private void resetCalc(){
        displayString = new StringBuilder();
        numLeftParen = 0;
    }
    
    //If displayString holds a valid input calculation string, pass to Calculator object, reset calc to display result
    //If there's no valid input calculation, warn user and do nothing else
    private void equalsHandler(){
        if(checkOperatorStatus() && (numLeftParen == 0)){
            try{
                String result = myCalculator.calculate(displayString.toString());
                resetCalc();
                displayString.append(result);
                updateDisplay();
            }
            catch(Exception x){
                JOptionPane.showMessageDialog(null, x.getMessage());
                resetCalc();
                updateDisplay();
            }
        }else{
            JOptionPane.showMessageDialog(null, "This is not a valid calculation! Remember to close all parentheses and never end your calculation with an operator!");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        multButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        leftParenButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        rightParenButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        displayFunctionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 560));
        setSize(new java.awt.Dimension(500, 560));

        buttonPanel.setPreferredSize(new java.awt.Dimension(488, 400));
        buttonPanel.setLayout(new java.awt.GridLayout(5, 4, 1, 1));

        sevenButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sevenButton.setText("7");
        sevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(sevenButton);

        eightButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        eightButton.setText("8");
        eightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(eightButton);

        nineButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nineButton.setText("9");
        nineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(nineButton);

        divButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        divButton.setText("/");
        divButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(divButton);

        fourButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fourButton.setText("4");
        fourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(fourButton);

        fiveButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fiveButton.setText("5");
        fiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(fiveButton);

        sixButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sixButton.setText("6");
        sixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(sixButton);

        multButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        multButton.setText("*");
        multButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(multButton);

        oneButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        oneButton.setText("1");
        oneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(oneButton);

        twoButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        twoButton.setText("2");
        twoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(twoButton);

        threeButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        threeButton.setText("3");
        threeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(threeButton);

        subButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        subButton.setText("-");
        subButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(subButton);

        leftParenButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        leftParenButton.setText("(");
        leftParenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftParenButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(leftParenButton);

        zeroButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        zeroButton.setText("0");
        zeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zeroButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(zeroButton);

        rightParenButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rightParenButton.setText(")");
        rightParenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightParenButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(rightParenButton);

        addButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addButton.setText("+");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(addButton);

        equalsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        equalsButton.setText("=");
        equalsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalsButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(equalsButton);

        clearButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(clearButton);

        displayFunctionLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        displayFunctionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        displayFunctionLabel.setText("0");
        displayFunctionLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        displayFunctionLabel.setMaximumSize(new java.awt.Dimension(396, 74));
        displayFunctionLabel.setPreferredSize(new java.awt.Dimension(396, 74));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayFunctionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(displayFunctionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenButtonMouseClicked
        numButtonHandler("7");
    }//GEN-LAST:event_sevenButtonMouseClicked

    private void eightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightButtonMouseClicked
        numButtonHandler("8");
    }//GEN-LAST:event_eightButtonMouseClicked

    private void nineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineButtonMouseClicked
        numButtonHandler("9");
    }//GEN-LAST:event_nineButtonMouseClicked

    private void fourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourButtonMouseClicked
        numButtonHandler("4");
    }//GEN-LAST:event_fourButtonMouseClicked

    private void fiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveButtonMouseClicked
        numButtonHandler("5");
    }//GEN-LAST:event_fiveButtonMouseClicked

    private void sixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixButtonMouseClicked
        numButtonHandler("6");
    }//GEN-LAST:event_sixButtonMouseClicked

    private void oneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneButtonMouseClicked
        numButtonHandler("1");
    }//GEN-LAST:event_oneButtonMouseClicked

    private void twoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoButtonMouseClicked
        numButtonHandler("2");
    }//GEN-LAST:event_twoButtonMouseClicked

    private void threeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeButtonMouseClicked
        numButtonHandler("3");
    }//GEN-LAST:event_threeButtonMouseClicked

    private void zeroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zeroButtonMouseClicked
        numButtonHandler("0");
    }//GEN-LAST:event_zeroButtonMouseClicked

    private void leftParenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftParenButtonMouseClicked
        parenHandler("(");
    }//GEN-LAST:event_leftParenButtonMouseClicked

    private void rightParenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightParenButtonMouseClicked
        parenHandler(")");
    }//GEN-LAST:event_rightParenButtonMouseClicked

    private void divButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divButtonMouseClicked
        operatorButtonHandler("/");
    }//GEN-LAST:event_divButtonMouseClicked

    private void multButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multButtonMouseClicked
        operatorButtonHandler("*");
    }//GEN-LAST:event_multButtonMouseClicked

    private void subButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subButtonMouseClicked
        operatorButtonHandler("-");
    }//GEN-LAST:event_subButtonMouseClicked

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        operatorButtonHandler("+");
    }//GEN-LAST:event_addButtonMouseClicked

    private void equalsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalsButtonMouseClicked
        operatorButtonHandler("=");
    }//GEN-LAST:event_equalsButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        operatorButtonHandler("C");
    }//GEN-LAST:event_clearButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcDisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcDisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcDisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcDisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcDisplayFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel displayFunctionLabel;
    private javax.swing.JButton divButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalsButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JButton leftParenButton;
    private javax.swing.JButton multButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton rightParenButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton subButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
